export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const CREATE_CATEGORIES_SUCCESS="CREATE_CATEGORIES_SUCCESS"
export const UPDATE_CATEGORIES_SUCCESS="UPDATE_CATEGORIES_SUCCESS"
export const REMOVE_CATEGORIES_SUCCESS="REMOVE_CATEGORIES_SUCCESS"


export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const REMOVE_PRODUCT_SUCCESS="REMOVE_PRODUCT_SUCCESS"

export const ADD_TO_CARD="ADD_TO_CARD"
export const REMOVE_FORM_CARD="REMOVE_FORM_CARD"

export const SHOW_HIDE_BACKBT="SHOW_HIDE_BACKBT"